// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbkWC0p-X41vZYNNxj6_LrG6adJWKJmgg',
    appId: '1:945622150069:web:71a398feacdef9413347fc',
    messagingSenderId: '945622150069',
    projectId: 'markahendricks-1709052795781',
    authDomain: 'markahendricks-1709052795781.firebaseapp.com',
    storageBucket: 'markahendricks-1709052795781.firebasestorage.app',
    measurementId: 'G-VEC1KCKYHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs5LWumPouXg_NVyqqaUCzQ9PfVCvrqqw',
    appId: '1:945622150069:android:bd23832ade1d958d3347fc',
    messagingSenderId: '945622150069',
    projectId: 'markahendricks-1709052795781',
    storageBucket: 'markahendricks-1709052795781.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDswXiRVv02vlylFM0lNAD-XSPxwKAN2gA',
    appId: '1:945622150069:ios:ccff27626b92a7173347fc',
    messagingSenderId: '945622150069',
    projectId: 'markahendricks-1709052795781',
    storageBucket: 'markahendricks-1709052795781.firebasestorage.app',
    iosBundleId: 'com.example.taskReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDswXiRVv02vlylFM0lNAD-XSPxwKAN2gA',
    appId: '1:945622150069:ios:ccff27626b92a7173347fc',
    messagingSenderId: '945622150069',
    projectId: 'markahendricks-1709052795781',
    storageBucket: 'markahendricks-1709052795781.firebasestorage.app',
    iosBundleId: 'com.example.taskReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjcNO92c9oC14-Gc9rAyu25FG494LqnuE',
    appId: '1:945622150069:web:b7e165ab3d5696863347fc',
    messagingSenderId: '945622150069',
    projectId: 'markahendricks-1709052795781',
    authDomain: 'markahendricks-1709052795781.firebaseapp.com',
    storageBucket: 'markahendricks-1709052795781.firebasestorage.app',
    measurementId: 'G-LKDHK62YF9',
  );
}
